### ISSUE TITLE
How can I get the values ?

### ISSUE THREAD

**Issue by teicors** [duoani/jquery.scheduler#1]
Hi duoani,
first of all great job ! I was looking for a similar piece of soft for my own project,and finally I discovered it.
I need your help: I'm not proud in html, jquery and so on, and I cannot figure out how catch  the marked hours: in the doc I found the example, but I cannot retrieve any value:your help would be very appreciated.
I think a line similar to
`var mystr = $('#test1').scheduler(data);`
 and the values (...001111000...) of the appointments are stored into mystr.
Thanks

**Comment by duoani** [comment]
`var myVal = $('#test1').scheduler('val');`

By the way, `$('#test1').scheduler('val')` will return an `object` as default. Sorry about lacking of documentation.

**Comment by duoani** [comment]
There is also a Vue.js implementation here.
[vue-scheduler](https://github.com/duoani/vue-scheduler)
